# Generated by Django 3.2.4 on 2021-06-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.IntegerField(primary_key=True, serialize=False)),
                ('boards_name', models.CharField(max_length=100)),
                ('boards_description', models.CharField(blank=True, max_length=250, null=True)),
                ('board_created_on', models.DateTimeField()),
                ('board_updated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.IntegerField(primary_key=True, serialize=False)),
                ('card_name', models.CharField(max_length=100)),
                ('card_description', models.CharField(blank=True, max_length=250, null=True)),
                ('card_created_on', models.DateTimeField(blank=True, null=True)),
                ('card_updated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'card',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('list_id', models.IntegerField(primary_key=True, serialize=False)),
                ('list_name', models.CharField(max_length=100)),
                ('list_description', models.CharField(blank=True, max_length=250, null=True)),
                ('list_created_on', models.DateTimeField()),
                ('list_updated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_type', models.IntegerField()),
                ('user_firstname', models.CharField(max_length=100)),
                ('user_lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('email_id', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
