# Generated by Django 3.2.4 on 2021-06-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardAttachment',
            fields=[
                ('card_attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('attachment_ref', models.TextField()),
                ('attachment_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'card_attachment',
                'managed': False,
            },
        ),
    ]
